services:
  openclawswitch:
    build: .
    ports:
      - "8356:8356"
    volumes:
      - ./data:/data
      - /root/.openclaw:/root/.openclaw
    pid: "host"
    privileged: true
    restart: always
